From jupyter/datascience-notebook 
MAINTAINER Taku Yoshioka <taku.yoshioka.4096@gmail.com>

USER root

USER jovyan

RUN pip install pymc3 matplotlib==1.5.3 sphinx nbsphinx sphinx_rtd_theme \
    numpydoc parse sphinxcontrib-bibtex
ENV MPLBACKEND Agg
